services:
  - type: web
    name: booksphere-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    healthCheckPath: /
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    envVars:
      - key: VITE_API_URL
        value: https://booksphere-backend.onrender.com
