services:
  - type: web
    name: booksphere-app
    env: node
    plan: starter
    buildCommand: npm run install-all && cd frontend && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false
